stages:
  - trigger

backend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/backend.yml
  rules:
    - changes:
        - backend/**/*

frontend:
  stage: trigger
  trigger:
    include:
      - local: .gitlab/frontend.yml
  rules:
    - changes:
        - frontend/**/*
