workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - static-check
  - unit-test
  - integration-test
  - build

variables:
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/frontend/.npm"

include:
  - local: .gitlab/backend.yml
  - local: .gitlab/frontend.yml
